// TT-013 audition gate driver: `npm run audio:audit`.
// Serves the repo on a free localhost port, opens tools/audio-audit.html?report=1 in headless
// Chrome, receives the measurements by POST, writes docs/audio-audit.md and exits non-zero on
// any failure. No dependencies beyond Node and an installed Chrome/Chromium
// (override the binary with CHROME=/path/to/chrome).
import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { readFile, stat, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, extname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TIMEOUT_MS = Number(process.env.AUDIT_TIMEOUT_MS) || 180000;
const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.json': 'application/json' };

function findChrome() {
  return process.env.CHROME || 'google-chrome';
}

function startServer(onResult) {
  const server = createServer(async (req, res) => {
    try {
      const url = new URL(req.url, 'http://x');
      if (req.method === 'POST' && url.pathname === '/__audit') {
        let body = '';
        for await (const chunk of req) body += chunk;
        res.writeHead(204).end();
        onResult(JSON.parse(body));
        return;
      }
      const file = resolve(root, '.' + decodeURIComponent(url.pathname));
      if (!file.startsWith(root + sep) || !(await stat(file)).isFile()) throw new Error('nope');
      res.writeHead(200, { 'Content-Type': types[extname(file)] || 'application/octet-stream', 'Cache-Control': 'no-store' });
      res.end(await readFile(file));
    } catch {
      res.writeHead(404).end('Not found');
    }
  });
  return new Promise((ok) => server.listen(0, '127.0.0.1', () => ok(server)));
}

function fmt(v) {
  return v === null || v === undefined || v === '' ? '' : String(v);
}

function markdown(result) {
  const lines = [
    '# Audio audition gate (TT-013)',
    '',
    `Generated by \`npm run audio:audit\` on ${new Date().toISOString().slice(0, 10)}. ` +
      'Every item is rendered through `OfflineAudioContext` in headless Chrome with the game\'s own master chain and bus levels ' +
      '(`src/ui/audio/synth.js#createChain`, `index.js#LEVELS`), mono, 44.1 kHz.',
    '',
    '**Criteria** - non-silent: RMS over the audible part > 0.005 - no clipping: peak < 0.99 ' +
      '(a note "limiter engaged" means peak > 0.85, where the soft safety limiter starts shaping) - ' +
      'duration: audible end (last sample above -40 dB re the item\'s peak) within +/-10 % of the declared length ' +
      '(SFX: `dur` in sfx.js; tunes: last note start + gate + release from the tune data) - ' +
      'reference tones: dominant frequency by zero crossings AND by FFT within +/-2 %. Ambiences and the mix are checked to keep sounding to the end of the window.',
    '',
    `**Result: ${result.ok ? 'PASS' : 'FAIL'}** - ${result.rows.length} items, ${result.failed ?? '?'} failed.`,
    '',
  ];
  if (result.error) lines.push('```', result.error, '```', '');
  lines.push('| kind | id | declared s | measured s | RMS | peak | pitch Hz (zero-x / FFT) | result | notes |');
  lines.push('|---|---|---:|---:|---:|---:|---:|---|---|');
  for (const r of result.rows) {
    const pitch = r.hz != null ? `${r.hz} / ${r.fft} (want ${r.expectHz})` : '';
    lines.push(`| ${r.kind} | ${r.id} | ${fmt(r.declared)} | ${r.measured} | ${r.rms} | ${r.peak} | ${pitch} | ${r.pass ? 'PASS' : '**FAIL**'} | ${r.notes || ''} |`);
  }
  lines.push('', `Browser: ${result.userAgent || 'n/a'}`, '');
  lines.push('Listen to everything on `tools/audio-demo.html` (`npm start`, then open `/tools/audio-demo.html`).', '');
  return lines.join('\n');
}

async function main() {
  let resolveResult;
  const gotResult = new Promise((ok) => { resolveResult = ok; });
  const server = await startServer((r) => resolveResult(r));
  const { port } = server.address();
  const profile = await mkdtemp(join(tmpdir(), 'tallyman-audit-'));
  const url = `http://127.0.0.1:${port}/tools/audio-audit.html?report=1`;
  const args = ['--headless=new', '--disable-gpu', '--no-first-run', '--no-default-browser-check', '--mute-audio',
    '--autoplay-policy=no-user-gesture-required', `--user-data-dir=${profile}`, url];
  const chrome = spawn(findChrome(), args, { stdio: ['ignore', 'ignore', 'pipe'] });
  let stderr = '';
  chrome.stderr.on('data', (d) => { stderr += d; });
  const exited = new Promise((ok) => chrome.on('exit', (code) => ok({ exited: code })));
  chrome.on('error', (e) => resolveResult({ ok: false, error: `could not start Chrome (${findChrome()}): ${e.message}`, rows: [] }));
  const timeout = new Promise((ok) => setTimeout(() => ok({ ok: false, error: `timed out after ${TIMEOUT_MS} ms`, rows: [] }), TIMEOUT_MS));

  let result = await Promise.race([gotResult, timeout, exited]);
  if ('exited' in result) result = { ok: false, error: `Chrome exited (${result.exited}) before reporting.\n${stderr.slice(-2000)}`, rows: [] };
  chrome.kill('SIGTERM');
  server.close();
  await new Promise((ok) => setTimeout(ok, 300));
  await rm(profile, { recursive: true, force: true }).catch(() => {});

  await writeFile(resolve(root, 'docs/audio-audit.md'), markdown(result));
  for (const r of result.rows) {
    console.log(`${r.pass ? 'PASS' : 'FAIL'}  ${r.kind.padEnd(8)} ${r.id.padEnd(28)} end ${String(r.measured).padStart(7)}s  rms ${String(r.rms).padStart(6)}  peak ${String(r.peak).padStart(5)}${r.hz != null ? `  ${r.hz}/${r.fft} Hz` : ''}${r.notes ? `  ${r.notes}` : ''}`);
  }
  if (result.error) console.error(result.error);
  console.log(`audio:audit ${result.ok ? 'PASS' : 'FAIL'} - ${result.rows.length} items, ${result.failed ?? '?'} failed. Wrote docs/audio-audit.md`);
  process.exit(result.ok ? 0 : 1);
}

main().catch((e) => { console.error(e); process.exit(1); });
