// Dev tool (run once, needs network): download the public-domain font8x8 headers by
// Daniel Hepper and generate src/ui/font8x8.js. The generated file is committed so the
// build never needs the network.  Usage: node tools/fetch-font.js
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BASE = 'https://raw.githubusercontent.com/dhepper/font8x8/master/';
const SOURCES = [
  { file: 'font8x8_basic.h', keep: (cp) => cp >= 0x20 && cp <= 0x7e },
  { file: 'font8x8_box.h', keep: (cp) => cp >= 0x2500 && cp <= 0x257f },
  { file: 'font8x8_block.h', keep: (cp) => cp >= 0x2580 && cp <= 0x259f },
];

// Hand-drawn additions. 'X' = ink; leftmost char = least significant bit (font8x8 order).
const CUSTOM = [
  {
    cp: 0xa3, name: 'pound sign (custom, C64-style)', rows: [
      '..XXXX..',
      '.XX..XX.',
      '.XX.....',
      'XXXXX...',
      '.XX.....',
      '.XX...X.',
      'XXXXXXX.',
      '........',
    ],
  },
  { cp: 0xe000, name: 'solid block cursor (private use)', rows: Array(8).fill('XXXXXXXX') },
];

/**
 * Convert an 8-row picture ('X' = ink, leftmost = bit 0) into 8 font bytes.
 * @param {string[]} rows
 * @returns {number[]}
 */
export function rowsToBytes(rows) {
  return rows.map((r) => [...r].reduce((b, c, i) => (c === 'X' ? b | (1 << i) : b), 0));
}

/**
 * Parse a font8x8 C header into [codepoint, bytes] pairs. Code points come from the array
 * position plus the base declared in the header ("unicode points U+XXXX - ..."), not from
 * the per-line comments, which are mislabelled upstream around U+2548-254B.
 * @param {string} src
 * @returns {Array<[number, number[]]>}
 */
export function parseHeader(src) {
  const base = /unicode points U\+([0-9A-Fa-f]{4})/.exec(src);
  if (!base) throw new Error('header lacks "unicode points U+XXXX"');
  const body = src.slice(src.indexOf('= {') + 3);
  const out = [];
  let cp = parseInt(base[1], 16);
  for (const m of body.matchAll(/\{([^{}]*)\}/g)) {
    const bytes = m[1].split(',').map((s) => parseInt(s.trim(), 16));
    if (bytes.length !== 8 || bytes.some((b) => !(b >= 0 && b <= 255))) throw new Error(`bad glyph U+${cp.toString(16)}`);
    out.push([cp++, bytes]);
  }
  return out;
}

const hex2 = (b) => b.toString(16).padStart(2, '0');
const label = (cp) => (cp >= 0x21 && cp <= 0x7e && cp !== 0x5c ? ` ${String.fromCodePoint(cp)}` : '');

async function main() {
  const glyphs = new Map();
  for (const { file, keep } of SOURCES) {
    const res = await fetch(BASE + file);
    if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
    const pairs = parseHeader(await res.text()).filter(([cp]) => keep(cp));
    for (const [cp, bytes] of pairs) glyphs.set(cp, bytes);
    console.log(`fetch-font: ${file} -> ${pairs.length} glyphs`);
  }
  for (const { cp, rows } of CUSTOM) glyphs.set(cp, rowsToBytes(rows));

  const lines = [...glyphs.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([cp, bytes]) => `  [0x${cp.toString(16).padStart(4, '0')}, '${bytes.map(hex2).join('')}'],${label(cp) ? ` //${label(cp)}` : ''}`);
  const customDoc = CUSTOM.map((c) => ` *   U+${c.cp.toString(16).toUpperCase().padStart(4, '0')} ${c.name}`).join('\n');

  const out = `// GENERATED by tools/fetch-font.js — do not edit by hand.
/**
 * 8x8 monochrome bitmap font for The Tallyman.
 *
 * Source: font8x8 by Daniel Hepper <daniel@hepper.net>, https://github.com/dhepper/font8x8
 *   (font8x8_basic.h U+0020-007E, font8x8_box.h U+2500-257F, font8x8_block.h U+2580-259F)
 *   based on Marcel Sondaar's font8x8.h and the IBM public-domain VGA fonts.
 * License: Public Domain.
 *
 * Custom additions (hand-drawn for this project, also public domain):
${customDoc}
 *
 * Encoding: 8 bytes per glyph, one per row top to bottom; bit 0 (LSB) is the leftmost pixel.
 */

const DATA = [
${lines.join('\n')}
];

/** @type {Map<number, Uint8Array>} codepoint -> 8 row bytes */
export const font8x8 = new Map(DATA.map(([cp, hex]) => [cp, Uint8Array.from(hex.match(/../g), (h) => parseInt(h, 16))]));

/** The solid block cursor glyph (private-use code point U+E000). */
export const CURSOR = '\\ue000';

/** Character drawn for any code point the font lacks. */
export const FALLBACK_CHAR = '?';

const FALLBACK = font8x8.get(0x3f);
const toCp = (ch) => (typeof ch === 'number' ? ch : String(ch).codePointAt(0));

/**
 * Whether the font has a glyph for a character (first code point of the string) or code point.
 * @param {string|number} ch
 * @returns {boolean}
 */
export function hasGlyph(ch) {
  return font8x8.has(toCp(ch));
}

/**
 * The 8 row bytes for a character or code point; unknown glyphs return the '?' glyph.
 * @param {string|number} ch
 * @returns {Uint8Array}
 */
export function glyphFor(ch) {
  return font8x8.get(toCp(ch)) ?? FALLBACK;
}
`;
  const dest = resolve(root, 'src/ui/font8x8.js');
  writeFileSync(dest, out);
  console.log(`fetch-font: wrote ${dest} (${glyphs.size} glyphs)`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => { console.error('fetch-font:', err.message); process.exit(1); });
}
